### ISSUE TITLE
[Data Filter] Limiter des filtres à un ou un ensemble de rôles spécifiques.

### ISSUE THREAD

**Issue by Gabrielbdry** [Recursyve/nestjs-librairies#58]
On veut faire en sorte que selon l'utilisateur seulement certains filtres sont envoyés au frontend, cela va dépendre du rôle, mais pourrait éventuellement dépendre des d'autres données de l'utilisateur.

**Comment by JulienDuf** [comment]
We could add a function `enable` in the configuration of a Filter.

```ts
export class MyFilter extends BaseFilter<MyFilterData> {
    public dataDefinition = MyFilterData;

    public test = new TextFilter({
        attribute: "test",
        enable: ({ user, req }) => true
    });
}
```
